# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# We need to install BiocInstaller for testing Bioconductor packages
bioc_required: true
